env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
plugins:
  - react