name: Release

on:
  - push
  # pull_request:
  #   types:
  #     - closed

jobs:
  release:
    # if: |
    #   github.event.pull_request.merged == true &&
    #   github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          VERSION=$(cat version)
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: ghashange/sendgrid-mock:${{ env.RELEASE_VERSION }}
