name: Test

on:
  - workflow_call
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install clean slate
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test  
        run: npm run test
